#!/bin/bash

# when run, will take any non-excluded dotfiles in this directory and check them against ~. If there's no valid symlink in ~ to a dotfile in this repo, it will make one. If ~ has a real file named the same as the dotfile in here, it will move it to 'olddir' before symlinking

# what it can't do is remove any symlinks in ~ that are no longer needed/invalid, you'll have to do that by hand.


dir=~/CODE/Scripts/Dotfiles/dotfiles # dotfiles directory
olddir=~/CODE/Scripts/Dotfiles/dotfiles_old # old dotfiles backup directory

if [[ ! -d "$olddir" ]]; then echo "making directory to house old dots, one level up from this script" && mkdir -p "$olddir"; fi

# make sure we're in the dotfiles directory, prob not needed
echo "Changing to the $dir directory"
cd "$dir"

# create an array with all the dotfiles in my dots dir
# [^.] is a negating expression to avoid matching . or ..  https://stackoverflow.com/a/31498096/3536094
arr=($dir/.[^.]*)

# some of below from https://koenwoortman.com/bash-script-check-if-file-is-symlink/, the multiple ifs because zsh doesn't seem to like any exclusion list-based array comparisons, and other solutions get too bsd vs gnu 
for dotfilepath in "${arr[@]}"; do
   dotfile="${dotfilepath##*/}" #filename only
   if [[ "$dotfile" = ".git" ]] ||  
      [[ "$dotfile" = ".config" ]] || # its a folder anywhay but is the XDG folder, and we'll deal with neovim in it separetly later
      [[ "$dotfile" = ".gitignore" ]] ||
      [[ "$dotfile" = *.swp ]] || # In case we have vim open on this file...
      [[ "$dotfile" = ".vim" ]] || # I swear we don't need that solarized colourscheme its installed by a package, if we do then curl it in instead
      [[ "$dotfile" = ".vscode" ]] || # that got me: its fine at first....until you open this repo with vscode and then re-run this! its a folder as well
      [[ "$dotfile" = ".codex" ]]  # we only symlink my config files from ~/.codex, not the whole folder! see below
   then echo "$dotfile is excluded"
   elif [[ -f "$HOME/$dotfile" ]] ; then
       #dotfile is already in ~, is it a valid symlink?
       if [[ -L "$HOME/$dotfile" && -e "$HOME/$dotfile" ]]; then # I see no point in second check?!?!
         echo "$dotfile already linked to dots, ignoring..."
       else 
         echo "$dotfile is not a symlink (or is a broken one) - we will move THEN copy to fix that"
         # so we need to move then copy
         mv "$HOME/$dotfile" "$olddir/"
         ln -s "$dotfilepath" "$HOME/$dotfile"
     fi 
   else echo "$dotfile doesn't exist in ~, linking..." && ln -s "$dotfilepath" "$HOME/$dotfile"
   fi 
done

# now do a similar operation for editor configs that use XDG, e.g. ~/.config/nvim
# symlink whole config folders from dotfiles into ~/.config
should_be_xdg_config_home=$HOME/.config

link_xdg_config_folder() {
    local config_name="$1"
    local source_config_dir="$dir/.config/$config_name"
    local target_config_dir="$should_be_xdg_config_home/$config_name"

    if [[ ! -d "$source_config_dir" ]]; then
        echo "Warning: $source_config_dir does not exist in dotfiles repo, skipping..."
        return
    fi

    if [[ ! -d "$should_be_xdg_config_home" ]] ; then
        echo "Wanted to symlink $config_name from dots, but there's no ~/.config, making one..."
        mkdir -p "$should_be_xdg_config_home"
    fi

    if [[ -L "$target_config_dir" ]]; then
        echo "$target_config_dir already linked to dots, ignoring..."
    elif [[ -e "$target_config_dir" ]]; then
        echo "$target_config_dir is not a symlink, moving then linking..."
        [[ -d "$olddir/.config" ]] || (echo "making a .config folder in $olddir to backup XDG config folders"; mkdir "$olddir/.config")
        echo "moving $target_config_dir to $olddir/.config"
        mv "$target_config_dir" "$olddir/.config"
        echo "linking $source_config_dir to $target_config_dir"
        ln -s "$source_config_dir" "$target_config_dir"
    else
        echo "$target_config_dir doesn't exist in ~, linking..."
        ln -s "$source_config_dir" "$target_config_dir"
    fi
}

link_xdg_config_folder nvim
link_xdg_config_folder lvim


# --- Codex config (to only capture config.toml and AGENTS.md instead of the definitely local-only stuff in ~/.codex) ---
codex_dir="$HOME/.codex"
dots_codex_dir="$dir/.codex"

codex_backup_dir="$olddir/.codex"

# Make sure ~/.codex exists
if [[ ! -d "$codex_dir" ]]; then
    echo "Creating $codex_dir for Codex data"
    mkdir -p "$codex_dir"
fi

# Make sure backup dir exists
if [[ ! -d "$codex_backup_dir" ]]; then
    echo "Creating $codex_backup_dir for old Codex config files"
    mkdir -p "$codex_backup_dir"
fi

# we can link either files or folders here, and nicely add new ones below
link_codex_path() {
    local kind="$1"
    local name="$2"
    local src="$dots_codex_dir/$name"
    local dest="$codex_dir/$name"

    if [[ "$kind" == "file" && ! -f "$src" ]]; then
        echo "Warning: $src does not exist in dotfiles repo, skipping..."
        return
    fi

    if [[ "$kind" == "folder" && ! -d "$src" ]]; then
        echo "Warning: $src does not exist in dotfiles repo, skipping..."
        return
    fi

    if [[ -L "$dest" ]]; then
        # already a symlink: ideally to our src
        echo "$dest already symlinked, leaving as is..."
    elif [[ -e "$dest" ]]; then
        # real file/folder (or something else), back it up then replace
        echo "$dest exists and is not a symlink, backing up then replacing..."
        mv "$dest" "$codex_backup_dir/"
        ln -s "$src" "$dest"
        echo "Linked $src -> $dest"
    else
        # doesn't exist at all, just create the link
        echo "$dest doesn't exist, linking..."
        ln -s "$src" "$dest"
    fi
}

link_codex_path file config.toml
link_codex_path file AGENTS.md
link_codex_path folder rules
link_codex_path folder skills

# general message to end
echo "remember you may need to source/reload some dotfiles before anything will change..."  
