#! /bin/bash

# Functions as a Homebrew and Homebrew/Cask setup script, as a running binary or app install script
# and as a running upgdate/upgrade scrupt for all of those

# I took the decision to always upgrade all my apps as I go along i.e.: when i run this script
# i.e.: I decided for this user's machine, i'd rather fear constant small problems than infrequent larger ones

echo "Checking for Homebrew and installing if we don't have it"
if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo "updating homebrew" && brew update

echo "before we update any packages, we may need some pins, to stop things being updated"
# YOU HAVE TO `brew unpin x` once you've pinned....
pins=(
		node
)
for pin in "${pins[@]}"; do { echo "don't update $pin" && brew pin "$pin"; } done


echo "upgrading already-installed formula - hold on to your seats!" && brew upgrade

# originally was see here "see https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md"
# but that page has been pulled, and see https://github.com/Homebrew/homebrew/issues/45862
# doesn't seem significant, but lets wait till the problem crops up again to investigate - what does the canned advice in the ruby script say?

#echo "mmaking sure that those directories haven't lost write access YET again"
#sudo chown $(whoami):admin /usr/local && sudo chown -R $(whoami):admin /usr/local

echo "calling the doctor to fix issues" && brew doctor

echo "Tapped taps:"
taps=(
		caskroom/cask
		# caskroom/games - retro emulators - but not investigated yet
)

tap_list=$(brew tap)
echo $tap_list && echo "let's tap any untapped taps..."
for tap in "${taps[@]}"; do { [[ $tap_list != *"$tap"* ]] && brew tap "$tap"; } done

echo "running brew cleanup" && brew cleanup

echo "Brewed binaries:"
bins=(
        ack
        antigen
		bash-completion #https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion
	 	#boot2docker - docker-machine now likes to download this for you and puts it /Users/twoode/.docker/machine/cache/boot2docker.iso 
		cmake #installed to setup YouCompleteMe vim plugin
		ctags-exuberant
        fswatch #for smoke's nodemon problem
        git
		groovy
		httpie #CLI HTTP client; user-friendly cURL replacement featuring intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc. http://httpie.org
		#mysql - using mamp's copy as my primary fot the meanwhile
        jq
		macvim --with-override-system-vim #https://stackoverflow.com/a/8539518/3536094 one reason i'm using macvim is clientserver support, another is some completion?
		node
        p7zip
		postgresql
        rmtrash
		tmate
        tmux
        tree
		reattach-to-user-namespace #required for pbcopy in tmux, your tmux.conf WILL crash without it
        #vim --with-client-server # see https://stackoverflow.com/a/25979565/3536094 would also require adding xquartz to cask (yes cask!)
		zsh
)

brew_list=$(brew list)
echo $brew_list && echo "let's brew any unbrewed bins..." 
for bin in "${bins[@]}"; do { [[ $brew_list != *"$bin"* ]] && brew install "$bin"; } done

# Applications is now cask's default folder to move apps to, no longer ~/Applications
# echo "let's remember casks go in /Applications" && export HOMEBREW_CASK_OPTS="--appdir=/Applications"

cask="brew cask"
install="$cask install"

echo "Installed casks:"
cask_list=$(brew cask list)
echo $cask_list

echo "Installing any non-installed Cask Apps"
apps=(
		aerial # beautiful screensaver
		alfred
		balsamiq-mockups
		blueharvest
		caffeine
		cord
		dash
		diffmerge
		disk-inventory-x
		docker-toolbox
		dropbox
		firefox
        flux
		freefilesync
		google-chrome
		google-drive
		iterm2
		java
		jd-gui #inspect java class files
        jetbrains-toolbox
		jumpcut
		mamp
		moom
		parallels-desktop
		pgadmin4
        paintbrush
		platypus
        postman
		regexhibit # regex tester using perl
		reggy # osx regex tester built in objective c
        rocket-chat #doesn't work needs to be updated from v1.3 to 2.7
        spotify
		skype
		slack
		snapz-pro-x
		sourcetree
		sublime-text
		teamviewer
        the-unarchiver
		tiddlywiki
		virtualbox
		virtualbox-extension-pack
)

for app in "${apps[@]}"; do { [[ $cask_list != *"$app"* ]] && $install "$app"; } done

echo "running the cask upgrade script (cask cannot upgrade progs automatically"
./cask_upgrade_script

echo "running cask cleanup" && brew cask cleanup

echo "I'm outta yer loop, cya"
 
