#!/bin/bash
cat <<"EOF"
instructions:
https://github.com/riyadhalnur/npm-modules-sync
   1. On the machine you want to use as the source of your package list, run `npm-sync init -t <your-github-token>`
   2. Note the ID of the gist returned from the previous step once it completes
   3. On the machine you want to sync using the the gist, run `npm-sync init -t <your-github-token> -i <gist-id>`
   4. Run `npm-sync up` subsequently on your main machine to update the list of packages
   5. Run `npm-sync dl` subsequently on your syned machines to download the current list of global packages


EOF

# and note there is scant alternative unless you do it yourself https://stackoverflow.com/questions/41583514/npm-how-to-sync-global-packages-between-different-computers

# we'll need a github token. note: As a security precaution, GitHub automatically removes personal access tokens that haven't been used in a year.
# settings > Developer Settings > Personal Access Tokens > Generate new token, then just tick gist as the scope, note you won't be able to see the token ever again.
tokenFile=./sync-npm-modules-github-token.conf
source $tokenFile # gives us github-token-for-gist-access and #github_gist_id
token="$github_token_for_gist_access"
gist=$github_gist_id
[[ ! -z $token ]] && echo "github token is: $token" || (echo "can't access your github token from $tokenFile, exiting..." && exit)
[[ ! -z $gist ]] && echo "github gist can be found at: https://gist.github.com/tonywoode/$gist" || (echo "can't access your github gist from $tokenFile, exiting..." && exit)
echo "try this in browser console to pretty print the gist from that url: JSON.parse(document.getElementById('file-modules-json-LC1').textContent)"
echo ""
# install npm-modules sync if you don't have it (make sure you've installed a version of node first (i think nvm installs lts by default)
if ! type "npm-sync" > /dev/null 2>&1; then
  echo "we need to install npm-modules-sync, installing globally..."
  npm install -g npm-modules-sync
fi
 
# bear in mind I already ran a gist creation from an initial machine which made me a gist id
read -s -n 1 -p "Press any key to do an INITIAL sync to this machine (for subsequent syncs read instructions above) . . ."
 echo ""
npm-sync init -t "$token" -i "$gist"
echo "note a bug if you have installed anything from your own filesystem, you'll have to delete it from the gist manually atm"
echo "I don't say much I did just finish....bye"
